# Default HTTP port
server:
  port-range: 8080-8099 
  

# HATEOAS resource links fix
  forward-headers-strategy: framework   
  
  
  
# Send data to admin server
spring:
  boot:
    admin:
      client:
        url: ${managementServerURL:http://127.0.0.1:8080}/admin


# Logging configuration    
logging:
  level:
    root: error
    org.springframework.security: debug
    org.springframework.web: debug   
    org.springframework.web.servlet.handle: off
    org.springframework.boot.context.config: debug
    com.netflix.discovery: off # Disable Eureka exception logging when management server is unreachable




# Allow actuator to expose statistics
management:
  endpoints:
    web:
      exposure: 
        include: 
          - '*'
      cors: 
        allowed-origins: 
          - '*'
    jmx:
      exposure:
        include: 
          - '*'      

# FIX /actuator/health alwoays returning DOWN
  health:
    defaults: 
      enabled: false       


# Register microservices to eureka main directory
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: ${managementServerURL:http://127.0.0.1:8080}/eureka/
  instance:
    preferIpAddress: true
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}
      
# Autoscan java annotation to detect JAX-RS annotated service to expose as @GET or @POST
cxf.jaxrs.component-scan: true


# Hystrix wraps calls to microservices to detect failure and redirect response to a common fallback response
# Circuit Breaker helps Hystrix by redirecting response automatically to fallback response if defined thresholds are reached 
# Parameters set according to : https://github.com/Netflix/Hystrix/wiki/Configuration
hystrix.command.default.execution.isolation.strategy: THREAD 
hystrix.command.default.execution.execution.timeout.enabled: false
hystrix.command.default.fallback.enabled: false
hystrix.command.default.circuitBreaker.enabled: false 
hystrix.command.default.metrics.rollingStats.timeInMilliseconds: 600000
hystrix.command.default.metrics.rollingStats.numBuckets: 600

