spring:
  application:
    name: EurekaServer
  boot:
    admin:
      context-path: /admin


logging:
  level:
    org.springframework.security: debug   
    com.netflix.discovery: off # Disable Eureka exception logging when management server is unreachable

server:
  port: 8761
  
eureka:
  client:
    enabled: true
    registerWithEureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:${server.port:8761}/eureka/
  instance:
    preferIpAddress: true
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
      
     
     